---

# ########## systemd
- block:
    - debug:
        msg: "configure systemd service"

  when:
    - app_service_merged|d(none)
    - app_service_merged.type|d(none) == 'system'
    - ansible_service_mgr == 'systemd'



# ########## rc.d
- block:
    - debug:
        msg: "configure rc.d service"

  when:
    - app_service_merged|d(none)
    - app_service_merged.type|d(none) == 'system'
    - ansible_service_mgr == 'bsdinit'



# ########## daemontools
- block:
    - name: create daemontools workspaces
      file:
        path: "{{ app_daemontools_dir }}/{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
        state: directory
      loop: "{{ app_daemontools_directories_template }}"

    - name: deploy daemontools run scripts
      template:
        src: "svscan/{{ item.path }}"
        dest: "{{ app_daemontools_dir }}/{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop: "{{ app_daemontools_scripts_template }}"

    - name: supervise (link) daemontools service
      file:
        src: "{{ app_daemontools_dir }}"
        dest: "{{ daemontools_svscan_dir }}/app_{{ app_name }}"
        state: link

  when:
    - app_service_merged|d(none)
    - app_service_merged.type|d(none) == 'daemontools'
