---

- block:
    - name: "get associated dataset for {{ app_base_dir }}"
      shell: zfs list | egrep '[[:blank:]]{{ app_base_dir }}$' | cut -d ' ' -f1
      register: app_base_dir_dataset
      changed_when: False

    - block:
        - name: "create dataset for {{ app_dir }}"
          zfs:
            name: "{{ app_base_dir_dataset.stdout }}/{{ app_name_full }}"
            state: present
            extra_zfs_properties: "{{ app_dir_zfs_properties }}"

        - name: set app_dir permissions
          file:
            path: "{{ app_dir }}"
            owner: "{{ app_dir_owner }}"
            group: "{{ app_group }}"
            mode: "{{ app_dir_permissions }}"

      when: app_base_dir_dataset.stdout != ""

  when: app_dir_type == 'try_zfs_dataset'
