---

- block:
    - include: accounts.yml
      vars:
        accounts_groups:
          - name: "{{ app_group }}"
            gid: "{{ app_group_id | d(omit) }}"
        accounts_users:
          - name: "{{ app_user }}"
            comment: "{{ app_user }}"
            group: "{{ app_group }}"
            home: "{{ app_user_homedir }}"
            shell: "{{ app_user_shell | d('/bin/sh') }}"
            uid: "{{ app_user_uid | d(omit) }}"
            home_mode: "{{ app_user_homedir_right | d('0750') }}"
            password: '*'
            ssh_auth_key: "{{ app_user_ssh_auth_key | d(None) }}"

- block:
    - include: accounts.yml
      vars:
        accounts_groups: []
        accounts_users:
          - name: "{{ app_user_run }}"
            comment: "{{ app_user_run }}"
            group: "{{ app_group }}"
            home: "{{ app_user_run_homedir }}"
            shell: "{{ app_user_run_shell | d('/bin/sh') }}"
            uid: "{{ app_user_run_id | d(omit) }}"
            home_mode: "{{ app_user_run_homedir_right | d('0750') }}"
            password: '*'
            ssh_auth_key: "{{ app_user_run_ssh_auth_key | d(None) }}"

    - name: deploy sudo to run user
      template:
        src: "sudoers.d/sudo_all"
        dest: "{{ sudoers_d_dir }}/{{ app_name_full }}_users"
        owner: root
        group:  "{{ root_group }}"
        mode: 0440
        validate: 'sh -c "cat {{ sudoers_file }} %s | visudo -cf-"'
      vars:
        sudo_from: "{{ app_user }}"
        sudo_to: "{{ app_user_run }}"

  when: app_user_run_want
