---

- block:
    - name: "get associated dataset for {{ app_base_dir }}"
      shell: zfs list -H "{{ app_base_dir }}" | awk '{print $1}'
      register: app_base_dir_dataset
      changed_when: False

    - block:
        - name: "create dataset for {{ app_dir }}"
          zfs:
            name: "{{ app_base_dir_dataset.stdout }}/{{ app_name_full }}"
            state: present
            extra_zfs_properties: "{{ app_dir_zfs_properties }}"

      when:
        - app_base_dir_dataset.rc == 0
        - app_base_dir_dataset.stdout != ""

  when: app_dir_type == 'try_zfs_dataset'
