---

- name: compute want_app
  set_fact:
    want_app: "{{ lookup('vars', 'want_app_' + app_name, default=false) }}"

- block:

    - include_tasks: context.yml

    - include_tasks: context_service.yml      

    - include_tasks: mandatory.yml

    - include: app_dir.yml

    - include: app_user.yml

    - include: app_packages.yml

    - include: app_workspace.yml

    # - include: app_db.yml

    # - include: app_nginx.yml

    # - include: app_service.yml

  when: want_app

- name: "set has_app_{{ app_name }}"
  set_fact:
    "has_app_{{ app_name }}": "{{ want_app }}"
