---

- name: setup workspace sub directory tree
  file:
    path: "{{ item.path | d(omit) }}"
    src: "{{ item.src | d(omit) }}"
    dest: "{{ item.dest | d(omit) }}"
    owner: "{{ item.owner | d(app_user) | d(app_default_user) }}"
    group: "{{ item.group | d(app_group) | d(app_default_group) }}"
    mode: "{{ item.mode | d(omit) }}"
    state: "{{ item.state|d('directory') }}"
  loop: "{{ workspace_sub_directories }}"
