#!/bin/sh

exec 2>&1

exec setuidgid \
{% if app_user_run_want %}
     "{{ app_user_run }}" \
     env HOME="{{ app_user_run_homedir }}" \
{% else %}
     "{{ app_user }}" \
     env HOME="{{ app_user_homedir }}" \
{% endif %}
     "{{ app_scripts_main }}" {{ app_scripts_main_start_arg|d('') }}
